// Code generated by mkskill. DO NOT EDIT.

package main

import (
	_ "embed"

	"github.com/pablo-botella/mkskill"
)

//go:embed mkskill_docs/README.md
var mkskillReadme string

//go:embed mkskill_docs/AGENTS.md
var mkskillAgents string

//go:embed mkskill_docs/SKILL.md
var mkskillSkill string

// MkskillSpec carries the composed documentation views, ready for the
// generate commands (mkskill.CheckParams and friends).
var MkskillSpec = mkskill.Spec{
	Name:        "mskblob",
	Description: "Simple blob born to give support to alternate storage in https://github.com/pablo-botella/miniskin since v0.3.12 but quite generic so it's just another blob. Use when working with mskblob/CLI — the github.com/pablo-botella/mskblob Go package and `.blob` pack-file format. Covers packing many assets into one external `.blob` sidecar (kept out of the Go binary), listing/accessing and serving them at runtime, the on-disk format, and the `mskblob` CLI. Triggers on `.blob` files, the mskblob package/CLI, or \"external asset blob / pack file\" tasks in Go projects.",
	Version:     "v0.5.3",
	Readme:      mkskillReadme,
	Agents:      mkskillAgents,
	Skill:       mkskillSkill,
}
